steps:
# Step 1: Install dependencies
- name: 'node:18'
  entrypoint: 'npm'
  args: ['install']

# Step 2: Build the React app
- name: 'node:18'
  entrypoint: 'npm'
  args: ['run', 'build']

# Step 3: Deploy the app to Google App Engine
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['app', 'deploy', '--quiet']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      versions=$(gcloud app versions list --sort-by '~version' --format 'value(version.id)' | tail -n +11)
      if [ ! -z "$versions" ]; then
        gcloud app versions delete $versions --quiet
      fi

options:
  logging: CLOUD_LOGGING_ONLY 

# Specify the App Engine service account if necessary
substitutions:
  _APP_ENGINE_SERVICE_ACCOUNT: 'cloudbuild@voxleads-api-stg-bv7a.iam.gserviceaccount.com'

timeout: '1200s'