steps:
# Step 1: Install dependencies
- name: 'node:18'
  entrypoint: 'npm'
  args: ['install']

# Step 2: Build the React app
- name: 'node:18'
  entrypoint: 'npm'
  args: ['run', 'build']
  env:
    - 'NODE_ENV=production'
    - 'REACT_APP_API_URL=${_API_URL}'

# Step 3: Copy appropriate app.yaml based on environment
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      cp app.${_DEPLOY_ENV}.yaml app.yaml

# Step 4: Deploy the app to Google App Engine
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['app', 'deploy', '--quiet']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      versions=$(gcloud app versions list -service default --sort-by '~version' --format 'value(version.id)' | tail -n +11)
      if [ ! -z "$versions" ]; then
        gcloud app versions delete $versions --quiet
      fi

options:
  logging: CLOUD_LOGGING_ONLY 

# Specify substitutions
substitutions:
  _DEPLOY_ENV: 'staging'  # Default to staging if not provided
  _APP_ENGINE_SERVICE_ACCOUNT: 'cloudbuild@voxleads-api-stg-bv7a.iam.gserviceaccount.com'
  _API_URL: 'https://voxleads-api-dot-voxleads-api-stg-bv7a.uc.r.appspot.com/api/v1'  # Default to staging API

timeout: '1200s'
